api_version: 1
runtime: python27
threadsafe: true

libraries:
- name: lxml
  version: latest

handlers:
- url: /_grow/assets/
  static_dir: dist/
  secure: always
- url: /_grow/api/.*
  script: extensions.grow_build_server.api
  secure: always
- url: /_grow/.*
  script: extensions.grow_build_server.backend
- url: /.*
  script: extensions.grow_build_server.app
